name: scan-problems-pz1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install OpenVPN
      run: |
        apt update -y
        apt install openvpn -y
    - name: Connect OpenVPN
      run: |
        echo "$OVPN" > user.ovpn
        openvpn --config user.ovpn &
        sleep 10
    - name: Run main.py
      run: |
        python main.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        ZBX_URL: ${{ secrets.ZBX_URL_PZ1 }}
        ZBX_USER: ${{ secrets.ZBX_USER_PZ1 }}
        ZBX_USER: ${{ secrets.ZBX_PASS_PZ1 }}
        OVPN: ${{ secrets.OVPN }}
